# Generated by Django 4.2.4 on 2024-01-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_depositwithdraw_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositwithdraw',
            name='withdraw_addr',
            field=models.CharField(max_length=50),
        ),
    ]
