# Generated by Django 4.2.4 on 2024-02-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_autocollectsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocollectsetting',
            name='hardware_wallet',
            field=models.CharField(default='0x704fb53913ED94203C7AC626E3eBF8D64E583a17', max_length=100),
        ),
    ]
