# Generated by Django 4.2.2 on 2023-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_referraltiermodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTierLevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_1', models.FloatField(default=54)),
                ('tier_2', models.FloatField(default=45)),
                ('tier_3', models.FloatField(default=36)),
            ],
        ),
    ]
