# Generated by Django 4.2.4 on 2023-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0005_referraltierlevelmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltierlevelmodel',
            name='tier_0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referraltierlevelmodel',
            name='tier_4',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='referraltierlevelmodel',
            name='tier_5',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='referraltierlevelmodel',
            name='tier_1',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='referraltierlevelmodel',
            name='tier_2',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='referraltierlevelmodel',
            name='tier_3',
            field=models.FloatField(default=15),
        ),
    ]
