# Generated by Django 4.2.4 on 2024-01-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0006_referraltierlevelmodel_tier_0_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralRelationship',
        ),
    ]
