# Generated by Django 4.2.2 on 2023-07-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_wallet_id_user_deposit_addr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwalletcredential',
            old_name='private_address',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='userwalletcredential',
            old_name='public_address',
            new_name='public_key',
        ),
    ]
