# Generated by Django 4.2.2 on 2023-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_refer_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_enabled_two_factor_auth',
            new_name='otp_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_auth_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_base32',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
