# Generated by Django 4.2.2 on 2023-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_is_enabled_two_factor_auth_user_otp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletcredential',
            name='tx_count',
            field=models.IntegerField(default=0),
        ),
    ]
