# Generated by Django 4.2.4 on 2023-10-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userwalletcredential_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parentEmail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='parent email address'),
        ),
    ]
