# Generated by Django 4.2.4 on 2023-10-19 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_parentemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parentEmail',
            new_name='parent_email',
        ),
    ]
