# Generated by Django 4.2.4 on 2023-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_mail_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iqdt_payout_amount',
            field=models.FloatField(default=0),
        ),
    ]
