# Generated by Django 4.2.4 on 2024-01-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_reward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletcredential',
            name='encryption_key',
            field=models.TextField(default=''),
        ),
    ]
