# Generated by Django 4.2.2 on 2023-07-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('contract', models.CharField(unique=True, verbose_name=50)),
                ('decimals', models.IntegerField()),
                ('price', models.FloatField()),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tokens.token')),
            ],
        ),
    ]
