# Generated by Django 4.2.2 on 2023-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_id',
        ),
        migrations.AlterField(
            model_name='token',
            name='contract',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='token',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
