# Generated by Django 4.2.2 on 2023-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_usertoken_prev_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='price',
        ),
        migrations.AddField(
            model_name='token',
            name='buy_price',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='token',
            name='sell_price',
            field=models.FloatField(default=1),
        ),
    ]
